apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
  namespace: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels:
        app: magento
    spec:
      containers:
        - name: magento
          image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/magento-app:latest
          ports:
            - containerPort: 80
