apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
  namespace: magento
spec:
  replicas: 2
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels:
        app: magento
    spec:
      containers:
        - name: magento
          image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/magento-app:latest
          ports:
            - containerPort: 80
          env:
            - name: MAGENTO_MODE
              value: production
