name: WordPress CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "dockerfiles/**"
      - "nginx-app/**"
      - "nginx-data/**"
      - "k8s/**"
      - ".github/workflows/wordpress-deploy.yml"
  workflow_dispatch:

jobs:
  build_push:
    runs-o
