name: Magento & WordPress CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "dockerfiles/**"
      - "nginx-app/**"
      - "nginx-data/**"
      - "k8s/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  build_push:
    runs-on: ubuntu-latest

    outputs:
      ecr_registry: ${{ steps.login-ecr.outputs.registry }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-ids: ${{ secrets.ECR_REGISTRY_ID }}

      # ðŸ”¹ WordPress Build & Push
      - name: Build WordPress Docker image
        run: |
          docker build -t wordpress:latest -f dockerfiles/wordpress/Dockerfile.wp ./dockerfiles/wordpress

      - name: Tag WordPress image
        run: |
          docker tag wordpress:latest ${{ steps.login-ecr.outputs.registry }}/wordpress:latest

      - name: Push WordPress image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/wordpress:latest

      # ðŸ”¹ Magento Build & Push
      - name: Build Magento Docker image
        run: |
          docker build -t magento:latest -f dockerfiles/magento/Dockerfile.magento ./dockerfiles/magento

      - name: Tag Magento image
        run: |
          docker tag magento:latest ${{ steps.login-ecr.outputs.registry }}/magento:latest

      - name: Push Magento image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/magento:latest

  deploy:
    needs: build_push
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name prod-eks-cluster --region us-east-1

      - name: Deploy WordPress container
        run: |
          kubectl set image deployment/wordpress wordpress=${{ steps.login-ecr.outputs.registry }}/wordpress:latest
          kubectl rollout status deployment/wordpress

      - name: Deploy Magento container
        run: |
          kubectl set image deployment/magento magento=${{ steps.login-ecr.outputs.registry }}/magento:latest
          kubectl rollout status deployment/magento
