name: Magento CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "magento/**"
      - ".github/workflows/magento-deploy.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (Magento â€“ eu-west-3)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Magento Docker image
        run: |
          docker build -t magento-app:latest ./magento

      - name: Tag Magento image
        run: |
          docker tag magento-app:latest \
          ${{ steps.login-ecr.outputs.registry }}/magento-app:latest

      - name: Push Magento image to ECR
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/magento-app:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region eu-west-3 \
            --name magento-cluster

      - name: Deploy Magento to EKS
        run: |
          kubectl apply -f magento/k8s/
